# Generated by Django 5.2.5 on 2025-09-02 11:42

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlocAuthorModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='acount.basemodel')),
                ('full_name', models.CharField(max_length=64)),
                ('avatar', models.ImageField(upload_to='blog-author/')),
                ('bio', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Blog author',
                'verbose_name_plural': 'Blog authors',
            },
            bases=('acount.basemodel',),
        ),
        migrations.CreateModel(
            name='BlogCategoryModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='acount.basemodel')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Blog category',
                'verbose_name_plural': 'Blog categories',
            },
            bases=('acount.basemodel',),
        ),
        migrations.CreateModel(
            name='BlogTagModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='acount.basemodel')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Blog tag',
                'verbose_name_plural': 'Blog tags',
            },
            bases=('acount.basemodel',),
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='acount.basemodel')),
                ('image', models.ImageField(upload_to='blog-post/')),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('DELETED', 'Deleted')], default='DRAFT', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='bloc.blocauthormodel')),
                ('category', models.ManyToManyField(related_name='blogs', to='bloc.blogcategorymodel')),
                ('tag', models.ManyToManyField(related_name='blogs', to='bloc.blogtagmodel')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
            bases=('acount.basemodel',),
        ),
    ]
