# Generated by Django 5.2.5 on 2025-08-25 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='authors/')),
            ],
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='recipes/')),
                ('category', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('updated_ad', models.DateTimeField(auto_now=True)),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloc.blogauthor')),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('blogauthor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bloc.blogauthor')),
                ('text', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=128)),
                ('updated_ad', models.DateTimeField(auto_now=True)),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bloc.blogauthor')),
            ],
            bases=('bloc.blogauthor',),
        ),
    ]
