# Generated by Django 5.2.5 on 2025-08-29 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlocAuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='authors/')),
            ],
        ),
        migrations.CreateModel(
            name='BlocCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BlocTagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BlogsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='recipes/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('updated_ad', models.DateTimeField(auto_now=True)),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor_model', to='bloc.blocauthormodel')),
                ('category', models.ManyToManyField(related_name='category_model', to='bloc.bloccategorymodel')),
                ('tag', models.ManyToManyField(related_name='tag_model', to='bloc.bloctagmodel')),
            ],
            options={
                'verbose_name': 'bloc_model',
                'verbose_name_plural': 'bloc_models  ',
            },
        ),
        migrations.CreateModel(
            name='BlogComentaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('updated_ad', models.DateTimeField(auto_now=True)),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_model', to='bloc.blogsmodel')),
            ],
        ),
    ]
