# Generated by Django 5.2.5 on 2025-09-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloc', '0002_blogviewmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='content',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='BlogViewModel',
        ),
    ]
