# Generated by Django 5.2.5 on 2025-09-02 16:14

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0001_initial'),
        ('bloc', '0003_alter_blogmodel_content_delete_blogviewmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.CreateModel(
            name='BlogViewModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='acount.basemodel')),
                ('user_ip', models.CharField(max_length=15)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='bloc.blogmodel')),
            ],
            options={
                'verbose_name': 'Blog view',
                'verbose_name_plural': 'Blog views',
            },
            bases=('acount.basemodel',),
        ),
    ]
